version: '3.9'

services:
  pccs:
    image: ghcr.io/edgelesssys/pccs
    #ports:
    #  - "58081:8081"
    environment:
      APIKEY: ${PCCS_APIKEY}

  aesmd:
    image: ghcr.io/initc3/sgx-aesm:2.19-buster
    volumes:
      - aesmd-socket:/var/run/aesmd
    devices:
      # NOTE in-kernel driver
      - /dev/sgx_enclave
      - /dev/sgx_provision
      # NOTE out-of-tree driver
      #- /dev/isgx

  ego-ra-server:
    image: ego-ra-server
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
      secrets:
        - signingkey
    depends_on:
      aesmd:
        condition: service_started
      pccs:
        condition: service_started
    volumes:
      - aesmd-socket:/var/run/aesmd
      - /etc/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf
    devices:
      # NOTE in-kernel driver
      - /dev/sgx_enclave
      - /dev/sgx_provision
      # NOTE out-of-tree driver
      #- /dev/isgx
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  ego-ra-client:
    image: ego-ra-client
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      ego-ra-server:
        condition: service_started
    entrypoint: ["ego-ra-client", "-a", "ego-ra-server:8081"]

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"

secrets:
  signingkey:
    file: ./private.pem
